import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

function lyrics(lines: [string, string, string][]): { lyricsKo: string; lyricsRomanized: string; lyricsEn: string } {
  return {
    lyricsKo: lines.map(l => l[0]).join("\n"),
    lyricsRomanized: lines.map(l => l[1]).join("\n"),
    lyricsEn: lines.map(l => l[2]).join("\n"),
  };
}

async function main() {
  // ── Fetch existing labels ───────────────────────────────────────────────────
  const starship = await prisma.label.findUnique({ where: { slug: "starship-entertainment" } });
  const jyp = await prisma.label.findUnique({ where: { slug: "jyp-entertainment" } });
  const hybe = await prisma.label.findUnique({ where: { slug: "hybe-entertainment" } });

  if (!starship || !jyp || !hybe) {
    throw new Error("Required labels not found. Run the main seed first.");
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // IVE
  // ═══════════════════════════════════════════════════════════════════════════
  const ive = await prisma.artist.upsert({
    where: { slug: "ive" },
    update: {},
    create: {
      slug: "ive",
      type: "GROUP",
      stageName: "IVE",
      debutYear: 2021,
      labelId: starship.id,
      bio: "IVE (아이브) is a six-member South Korean girl group formed by Starship Entertainment, debuting on December 1, 2021. The group consists of Yujin, Gaeul, Rei, Wonyoung, Liz, and Leeseo. They are known for their sophisticated, confident concept and have become one of the defining fourth-generation K-pop acts.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/IVE_in_2023_%28cropped%29.jpg/960px-IVE_in_2023_%28cropped%29.jpg",
    },
  });

  // IVE Albums
  const iveAlbum1 = await prisma.album.upsert({
    where: { slug: "ive-eleven" },
    update: {},
    create: {
      slug: "ive-eleven",
      title: "ELEVEN",
      artistId: ive.id,
      releaseYear: 2021,
      type: "SINGLE",
      coverArt: "https://upload.wikimedia.org/wikipedia/en/thumb/3/37/IVE_-_Eleven.png/220px-IVE_-_Eleven.png",
    },
  });

  const iveAlbum2 = await prisma.album.upsert({
    where: { slug: "ive-ive" },
    update: {},
    create: {
      slug: "ive-ive",
      title: "IVE IVE",
      artistId: ive.id,
      releaseYear: 2023,
      type: "ALBUM",
      coverArt: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/IVE_-_I%27ve_IVE.png/220px-IVE_-_I%27ve_IVE.png",
    },
  });

  // IVE Songs
  const iveLoveDive = await prisma.song.upsert({
    where: { slug: "ive-love-dive" },
    update: {},
    create: {
      slug: "ive-love-dive",
      title: "LOVE DIVE",
      albumId: iveAlbum1.id,
      releaseYear: 2022,
      ...lyrics([
        ["나르시스처럼 난 내 눈에 빠져", "Nareusiseuceoreom nan nae nune ppajyeo", "Like Narcissus, I fall into my own eyes"],
        ["근데 왜 이 호수엔 네 얼굴이 보여", "Geunde wae i hosuaen ne eolguri boyeo", "But why do I see your face in this lake"],
        ["확인하고 싶어 내가 널 원하는 건지", "Hwagin hago sipeo naega neol wonhaneun geonji", "I want to confirm whether I want you"],
        ["아님 내 기분에 취해서 그런 건지", "Anim nae gibune chwiaeseo geureon geonji", "Or if I'm just intoxicated by my own feelings"],
        ["", "", ""],
        ["들어봐 내 심장 소리가", "Deureobwa nae simjang soriga", "Listen to the sound of my heart"],
        ["오늘따라 더 크게 들려", "Oneulttara deo keuge deullyeo", "It sounds louder than usual today"],
        ["이건 분명히 너 때문이야", "Igeon bunmyeonghi neo ttaemuniya", "This is clearly because of you"],
        ["Love dive into my eyes", "Love dive into my eyes", "Love dive into my eyes"],
        ["Love dive into my eyes", "Love dive into my eyes", "Love dive into my eyes"],
        ["", "", ""],
        ["내 맘속에 풍덩 뛰어들어", "Nae mamsogeul pungdeong ttwieodeulleo", "Dive deep into my heart"],
        ["I love, I love, I love dive", "I love, I love, I love dive", "I love, I love, I love dive"],
        ["한 치 앞도 안 보여도", "Han chi apdo an boyeodo", "Even when I can't see an inch ahead"],
        ["그냥 여기 있어줘", "Geunyangnyeo yeogie isseojweo", "Just stay here with me"],
        ["", "", ""],
        ["헷갈려 아직도 사랑인지 집착인지", "Hetgallyeo ajikdo saranginji jipchaginji", "I'm confused, still unsure if it's love or obsession"],
        ["설레는 이 기분을 어떻게 설명하지", "Seolle neun i gibeumeul eotteoke seolmyeonghaji", "How do I explain this fluttering feeling"],
        ["너무 좋아 겁이 날 정도야", "Neomu joa geopi nal jeongdoya", "I like you so much it scares me"],
        ["이 감정에 솔직하게 따라가 볼까", "I gamjeonge soljikage ttaragaga bolkka", "Should I honestly follow this feeling"],
        ["", "", ""],
        ["아름다운 착각이라도 괜찮아", "Areumdaun chakgagiraedo gwaenchana", "Even a beautiful illusion is fine"],
        ["이 순간만큼은 진심이야", "I sunganmankeumeun jinsimiya", "At least in this moment, it's sincere"],
        ["나를 바라보는 네 두 눈이", "Nareul baraborneun ne du nuni", "Your two eyes looking at me"],
        ["날 숨 막히게 해", "Nal sum makige hae", "Leave me breathless"],
        ["", "", ""],
        ["들어봐 내 심장 소리가", "Deureobwa nae simjang soriga", "Listen to the sound of my heart"],
        ["오늘따라 더 크게 들려", "Oneulttara deo keuge deullyeo", "It sounds louder than usual today"],
        ["이건 분명히 너 때문이야", "Igeon bunmyeonghi neo ttaemuniya", "This is clearly because of you"],
        ["Love dive into my eyes", "Love dive into my eyes", "Love dive into my eyes"],
        ["", "", ""],
        ["내 맘속에 풍덩 뛰어들어", "Nae mamsogeul pungdeong ttwieodeulleo", "Dive deep into my heart"],
        ["I love, I love, I love dive", "I love, I love, I love dive", "I love, I love, I love dive"],
        ["한 치 앞도 안 보여도", "Han chi apdo an boyeodo", "Even when I can't see an inch ahead"],
        ["그냥 여기 있어줘", "Geunyangnyeo yeogie isseojweo", "Just stay here with me"],
        ["", "", ""],
        ["Love dive, love dive", "Love dive, love dive", "Love dive, love dive"],
        ["깊이 빠져들어", "Gipi ppajyeodeulleo", "Fall deeper"],
        ["Love dive, love dive", "Love dive, love dive", "Love dive, love dive"],
        ["나에게로 와", "Naegero wa", "Come to me"],
      ]),
    },
  });

  const iveAfterLike = await prisma.song.upsert({
    where: { slug: "ive-after-like" },
    update: {},
    create: {
      slug: "ive-after-like",
      title: "After LIKE",
      albumId: iveAlbum1.id,
      releaseYear: 2022,
      ...lyrics([
        ["Like 다음엔 뭐가 와", "Like daeumena mwoga wa", "What comes after Like"],
        ["그 감정이 뭔지 몰라", "Geu gamjeongi mwonji molla", "I don't know what that feeling is"],
        ["두근두근 설레는 거 알아", "Dugeundugeun seolreneun geo ara", "I know this flutter, this excitement"],
        ["근데 너는 나를 좋아하니", "Geunde neoneun nareul joahani", "But do you like me"],
        ["", "", ""],
        ["I feel the love right now", "I feel the love right now", "I feel the love right now"],
        ["이게 사랑인 건지", "Ige sarangin geonji", "Is this what love is"],
        ["아직 잘 모르겠어", "Ajik jal moreugesseo", "I'm still not sure"],
        ["하지만 네 옆에 있고 싶어", "Hajiman ne yeopae itgo sipeo", "But I want to be by your side"],
        ["", "", ""],
        ["Like 한 다음엔 뭘 해야 해", "Like han daeumena mwol haeya hae", "What should I do after hitting Like"],
        ["Follow 누르면 되는 건가", "Follow nureurimyeon doeneun geonga", "Should I press Follow"],
        ["너의 DM이 오길 기다려", "Neoui DM-i ogil gidalyeo", "I'm waiting for your DM"],
        ["이게 다 뭔지 설명해줘", "Ige da mwonji seolmyeonghaejweo", "Explain to me what all of this is"],
        ["", "", ""],
        ["After like, what's next", "After like, what's next", "After like, what's next"],
        ["이 다음 단계가 뭔지", "I daeum dangyega mwonji", "What's the next step"],
        ["조금씩 다가오는 너", "Jogeumssik dagaoneun neo", "You slowly getting closer"],
        ["설레서 어쩔 줄 몰라", "Seolleseo eojjeol jul molla", "I don't know what to do with this excitement"],
        ["", "", ""],
        ["심장이 터질 것 같아", "Simjangi teojil geot gata", "My heart feels like it might burst"],
        ["이런 기분 처음이야", "Ireon gibun cheoeumeiya", "This feeling is a first for me"],
        ["네가 웃을 때마다", "Nega useul ttaemada", "Every time you smile"],
        ["나도 모르게 웃고 있어", "Nado moreuge utgo isseo", "I'm smiling without realizing it"],
        ["", "", ""],
        ["After LIKE, after LIKE", "After LIKE, after LIKE", "After LIKE, after LIKE"],
        ["너를 향한 이 마음", "Neoreul hyanghan i maeum", "These feelings aimed at you"],
        ["점점 커져가고 있어", "Jeomjeom keojyeogago isseo", "Are growing bigger and bigger"],
        ["멈출 수가 없어", "Meomchul suga eopseo", "I can't stop it"],
        ["", "", ""],
        ["Like 다음엔 뭐가 올까", "Like daeumena mwoga olkka", "What will come after Like"],
        ["Love가 오는 건 아닐까", "Love-ga oneun geon animkka", "Could Love be coming"],
        ["그 답을 알고 싶어서", "Geu dabeul algo sipeoeo", "Because I want to know that answer"],
        ["오늘도 네 곁에 있어", "Oneuldo ne gyeote isseo", "I'm by your side today too"],
      ]),
    },
  });

  const iveIAm = await prisma.song.upsert({
    where: { slug: "ive-i-am" },
    update: {},
    create: {
      slug: "ive-i-am",
      title: "I AM",
      albumId: iveAlbum2.id,
      releaseYear: 2023,
      ...lyrics([
        ["I am what I am", "I am what I am", "I am what I am"],
        ["나를 사랑하는 법을 배워가고 있어", "Nareul saranghaneun beobeul baewogago isseo", "I'm learning how to love myself"],
        ["완벽하지 않아도 괜찮아", "Wanbyeokhaji anado gwaenchana", "It's okay that I'm not perfect"],
        ["있는 그대로의 나를 믿어", "Inneun geudaeroeui nareul midyeo", "I trust myself just as I am"],
        ["", "", ""],
        ["두려움도 있어 가끔은", "Duryeoumdo isseo gakkeumeun", "I have fears sometimes"],
        ["흔들리는 순간들도 있어", "Heundeullineun sungandeuldo isseo", "There are moments when I waver"],
        ["하지만 그 안에서도", "Hajiman geu aneseo do", "But even within that"],
        ["내 빛을 잃지 않을 거야", "Nae bicheul ilchi aneul geoya", "I won't lose my light"],
        ["", "", ""],
        ["I am, I am, I am", "I am, I am, I am", "I am, I am, I am"],
        ["오직 나만의 길을 걸어가", "Ojik namaneui gireul georeoga", "I walk only my own path"],
        ["I am, I am, I am", "I am, I am, I am", "I am, I am, I am"],
        ["세상이 뭐라 해도", "Sesangi mwora haedo", "No matter what the world says"],
        ["난 나야", "Nan naya", "I am me"],
        ["", "", ""],
        ["누군가의 시선에 맞추지 않아", "Nugunga ui siseonae matchuji ana", "I don't conform to anyone's gaze"],
        ["내 기준으로 살아가", "Nae gijuneu ro saraaga", "I live by my own standards"],
        ["내가 정의하는 나의 아름다움", "Naega jeonguihaneun naui areumdaum", "The beauty that I define for myself"],
        ["그게 진짜 나야", "Geuge jinjja naya", "That's the real me"],
        ["", "", ""],
        ["상처받은 날들도 있었어", "Sangcheobabeun naldeuldo isseosseo", "There were days I was hurt"],
        ["눈물이 흘렀던 밤도 있었어", "Nunmuri heulleotteon bamdo isseosseo", "There were nights I cried"],
        ["하지만 그 모든 순간들이", "Hajiman geu modeun sungandeuri", "But all those moments"],
        ["지금의 나를 만들었어", "Jigeumui nareul mandeureosseo", "Made who I am now"],
        ["", "", ""],
        ["I am, I am, I am", "I am, I am, I am", "I am, I am, I am"],
        ["오직 나만의 길을 걸어가", "Ojik namaneui gireul georeoga", "I walk only my own path"],
        ["I am, I am, I am", "I am, I am, I am", "I am, I am, I am"],
        ["세상이 뭐라 해도", "Sesangi mwora haedo", "No matter what the world says"],
        ["난 나야", "Nan naya", "I am me"],
        ["", "", ""],
        ["I am what I am", "I am what I am", "I am what I am"],
        ["그게 전부야", "Geuge jeonbuya", "That's everything"],
        ["I am what I am", "I am what I am", "I am what I am"],
        ["그것으로 충분해", "Geugoseuro chungbunhae", "That's enough"],
      ]),
    },
  });

  const iveKitsch = await prisma.song.upsert({
    where: { slug: "ive-kitsch" },
    update: {},
    create: {
      slug: "ive-kitsch",
      title: "Kitsch",
      albumId: iveAlbum2.id,
      releaseYear: 2023,
      ...lyrics([
        ["이래도 되는 건지", "Iraedo doeneun geonji", "Is it okay to be like this"],
        ["너무 좋아서 숨겨왔던 마음", "Neomu joaseo sumgyeowatteon maeum", "These feelings I've been hiding because I like you so much"],
        ["말해도 될까봐 두려웠어", "Malhaedo doelkkabwa duryeowosseo", "I was afraid of whether I could even say it"],
        ["이제는 말할게", "Ijeneun malhalge", "Now I'll tell you"],
        ["", "", ""],
        ["Kitsch하게 물들어가", "Kitsch-hage muldeureoga", "Getting dyed in a kitsch way"],
        ["너라는 색으로", "Neoraneun saegeu ro", "The color that is you"],
        ["진부하게 사랑에 빠져", "Jinbuhage sarange ppajyeo", "Falling in love in the most cliché way"],
        ["하지만 설레는 걸 어떡해", "Hajiman seollereneun geol eotteokhae", "But what can I do when my heart flutters"],
        ["", "", ""],
        ["나 지금 너무 솔직한 건지도 몰라", "Na jigeum neomu soljikhan geonjido molla", "Maybe I'm being too honest right now"],
        ["이런 고백 흔하잖아", "Ireon gobaek heunhajanha", "This kind of confession is common"],
        ["근데 어떻게 이 마음을 숨기겠어", "Geunde eotteoke i maeeumeul sumgigessseo", "But how could I hide these feelings"],
        ["네 앞에서는", "Ne apeseo neun", "In front of you"],
        ["", "", ""],
        ["Kitsch해도 괜찮아", "Kitsch-haedo gwaenchana", "It's okay to be kitsch"],
        ["진부해도 상관없어", "Jinbuhaedo sanggwaneopseo", "I don't care if it's cliché"],
        ["이 감정이 진심이라면", "I gamjeongi jinsimiranimyeon", "If this feeling is genuine"],
        ["그걸로 충분해", "Geugeollo chungbunhae", "That's enough"],
        ["", "", ""],
        ["너의 웃음이 보고 싶어", "Neoui useumi bogo sipeo", "I want to see your smile"],
        ["오늘도 내일도 모레도", "Oneuldo naeildo moraeindo", "Today, tomorrow, and the day after"],
        ["평범한 일상 속에서도", "Pyeongbeomhan ilsang sogeseo do", "Even in the most ordinary daily life"],
        ["넌 특별해 나한테", "Neon teukbyeorhae nahante", "You're special to me"],
        ["", "", ""],
        ["Kitsch하게 물들어가", "Kitsch-hage muldeureoga", "Getting dyed in a kitsch way"],
        ["너라는 색으로", "Neoraneun saegeu ro", "The color that is you"],
        ["진부하게 사랑에 빠져", "Jinbuhage sarange ppajyeo", "Falling in love in the most cliché way"],
        ["하지만 설레는 걸 어떡해", "Hajiman seollereneun geol eotteokhae", "But what can I do when my heart flutters"],
        ["", "", ""],
        ["이게 사랑이라면", "Ige sarangiranimyeon", "If this is love"],
        ["Kitsch해도 돼", "Kitsch-haedo dwae", "It's okay to be kitsch"],
        ["너를 향한 마음은", "Neoreul hyanghan maeeumeun", "These feelings towards you"],
        ["진짜야", "Jinjjaya", "Are real"],
      ]),
    },
  });

  const iveBaddie = await prisma.song.upsert({
    where: { slug: "ive-baddie" },
    update: {},
    create: {
      slug: "ive-baddie",
      title: "Baddie",
      albumId: iveAlbum2.id,
      releaseYear: 2023,
      ...lyrics([
        ["I'm a baddie, baddie", "I'm a baddie, baddie", "I'm a baddie, baddie"],
        ["나를 봐, 눈 못 떼잖아", "Nareul bwa, nun mot ttaejanha", "Look at me, you can't take your eyes off"],
        ["I'm a baddie, baddie", "I'm a baddie, baddie", "I'm a baddie, baddie"],
        ["확실히 달라 나는", "Hwaksilhi dalla naneun", "I'm clearly different"],
        ["", "", ""],
        ["걸을 때마다 시선이 쏠려", "Georeul ttaemada sisyeoni ssollyeo", "Eyes follow me with every step I take"],
        ["뭔가 달라 오늘의 나", "Mwonga dalla oneurui na", "There's something different about me today"],
        ["자신감 넘쳐흘러", "Jasingam neomchyeoheulle o", "Overflowing with confidence"],
        ["이게 바로 나야", "Ige baro naya", "This is exactly who I am"],
        ["", "", ""],
        ["두려움? 그런 거 없어", "Duryeoum? Geureon geo eopseo", "Fear? I don't have such a thing"],
        ["내 앞에 뭐가 있든", "Nae apae mwoga itdeun", "Whatever stands before me"],
        ["당당하게 맞서 나가", "Dangdanghage majseo naga", "I face it head-on with confidence"],
        ["그게 바로 Baddie", "Geuge baro Baddie", "That's exactly what a Baddie is"],
        ["", "", ""],
        ["Baddie, baddie, I'm a baddie", "Baddie, baddie, I'm a baddie", "Baddie, baddie, I'm a baddie"],
        ["세상이 내 무대야", "Sesangi nae mudaeya", "The world is my stage"],
        ["Baddie, baddie, I'm a baddie", "Baddie, baddie, I'm a baddie", "Baddie, baddie, I'm a baddie"],
        ["내 방식대로 살아가", "Nae bangsikdaero saraaga", "I live life my own way"],
        ["", "", ""],
        ["완벽하지 않아도 괜찮아", "Wanbyeokhaji anado gwaenchana", "Even if I'm not perfect, it's fine"],
        ["그게 나의 매력이니까", "Geuge naui maeryeoginiikka", "That's part of my charm"],
        ["남들 시선 신경 쓰지 마", "Namdeul siseon singyeong sseuji ma", "Don't worry about what others think"],
        ["네 자신을 믿어", "Ne jasineul midyeo", "Trust yourself"],
        ["", "", ""],
        ["I'm a baddie, baddie", "I'm a baddie, baddie", "I'm a baddie, baddie"],
        ["나를 봐, 눈 못 떼잖아", "Nareul bwa, nun mot ttaejanha", "Look at me, you can't take your eyes off"],
        ["I'm a baddie, baddie", "I'm a baddie, baddie", "I'm a baddie, baddie"],
        ["확실히 달라 나는", "Hwaksilhi dalla naneun", "I'm clearly different"],
        ["", "", ""],
        ["오늘도 내일도 나는 Baddie", "Oneuldo naeildo naneun Baddie", "Today and tomorrow I'm a Baddie"],
        ["이게 바로 나야", "Ige baro naya", "This is exactly who I am"],
        ["세상아 다 들어라", "Sesanga da deureora", "Listen up, world"],
        ["나는 Baddie", "Naneun Baddie", "I am a Baddie"],
      ]),
    },
  });

  // IVE SongCredits
  for (const song of [iveLoveDive, iveAfterLike, iveIAm, iveKitsch, iveBaddie]) {
    await prisma.songCredit.upsert({
      where: { id: `credit-${song.slug}-ive` },
      update: {},
      create: { id: `credit-${song.slug}-ive`, songId: song.id, artistId: ive.id, role: "performer" },
    });
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // STRAY KIDS
  // ═══════════════════════════════════════════════════════════════════════════
  const strayKids = await prisma.artist.upsert({
    where: { slug: "stray-kids" },
    update: {},
    create: {
      slug: "stray-kids",
      type: "GROUP",
      stageName: "Stray Kids",
      debutYear: 2018,
      labelId: jyp.id,
      bio: "Stray Kids (스트레이 키즈) is an eight-member South Korean boy group formed by JYP Entertainment through the reality show of the same name in 2017, debuting on March 25, 2018. Known for self-producing a large portion of their music through their in-house unit 3RACHA (Bang Chan, Changbin, Han), Stray Kids have become one of the most distinctive and commercially successful acts of the fourth generation.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Stray_Kids_at_2022_MAMA_Awards.jpg/960px-Stray_Kids_at_2022_MAMA_Awards.jpg",
    },
  });

  const skzAlbum1 = await prisma.album.upsert({
    where: { slug: "skz-go-live" },
    update: {},
    create: {
      slug: "skz-go-live",
      title: "GO生 (GO LIVE)",
      artistId: strayKids.id,
      releaseYear: 2020,
      type: "ALBUM",
      coverArt: "https://upload.wikimedia.org/wikipedia/en/thumb/6/69/Stray_Kids_-_Go_Live.png/220px-Stray_Kids_-_Go_Live.png",
    },
  });

  const skzAlbum2 = await prisma.album.upsert({
    where: { slug: "skz-noeasy" },
    update: {},
    create: {
      slug: "skz-noeasy",
      title: "NOEASY",
      artistId: strayKids.id,
      releaseYear: 2021,
      type: "ALBUM",
      coverArt: "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Stray_Kids_-_Noeasy.png/220px-Stray_Kids_-_Noeasy.png",
    },
  });

  const skzGodsMenu = await prisma.song.upsert({
    where: { slug: "stray-kids-gods-menu" },
    update: {},
    create: {
      slug: "stray-kids-gods-menu",
      title: "God's Menu (神메뉴)",
      albumId: skzAlbum1.id,
      releaseYear: 2020,
      ...lyrics([
        ["들어와 들어와 우리 식당으로", "Deureo wa deureo wa uri sikdangeu ro", "Come in, come in, to our restaurant"],
        ["특별한 메뉴가 준비되어 있어", "Teukbyeolhan menyuga junbidoeeo isseo", "A special menu is prepared"],
        ["맛을 봐 맛을 봐 이건 다른 거야", "Maseul bwa maseul bwa igeon dareun geoya", "Taste it, taste it, this is different"],
        ["한번 먹으면 중독되는 맛", "Hanbeon meogeumyeon jungdokdoeneun mat", "Once you taste it, you'll be addicted"],
        ["", "", ""],
        ["God's menu 신이 내린 메뉴", "God's menu sin-i naerin menyu", "God's menu, a menu given by God"],
        ["이건 레시피가 없어", "Igeon resipiga eopseo", "This has no recipe"],
        ["우리만이 만들 수 있는", "Urimani mandeul su inneun", "Only we can make this"],
        ["특별한 한 끼", "Teukbyeolhan han kki", "A special meal"],
        ["", "", ""],
        ["매운맛 단맛 쓴맛 신맛", "Maeunmat danmat sseunmat sinmat", "Spicy, sweet, bitter, sour"],
        ["모든 맛을 다 담았어", "Modeun maseul da damaosseo", "We've put in every flavor"],
        ["너의 입맛에 맞게", "Neoui inmase maatge", "Tailored to your taste"],
        ["우리가 요리했어", "Uriga yorihaeosseo", "We cooked it for you"],
        ["", "", ""],
        ["좀 더 세게 불을 키워", "Jom deo sege bureul kiweo", "Turn up the heat a little more"],
        ["이제 시작이야 본격적으로", "Ije sijagiya bongyeokjeogeuro", "Now it's starting in earnest"],
        ["우리 식당의 대표 메뉴", "Uri sikdangui daepyo menyu", "The signature menu of our restaurant"],
        ["맛이 없을 리가 없어", "Masi eopseul riga eopseo", "There's no way it won't be delicious"],
        ["", "", ""],
        ["God's menu 지금 당장 맛봐", "God's menu jigeum dangjang massbwa", "God's menu, taste it right now"],
        ["이 맛을 알면 다른 건 못 먹어", "I maseul almyeon dareun geon mot meogeo", "Once you know this taste, you can't eat anything else"],
        ["중독성 강한 우리의 맛", "Jungdokseong ganghan uriui mat", "Our highly addictive flavor"],
        ["한번 빠지면 못 나와", "Hanbeon ppajimyeon mot nawa", "Once you fall for it, you can't get out"],
        ["", "", ""],
        ["Spicy, spicy, 매워 매워", "Spicy, spicy, maewo maewo", "Spicy, spicy, so spicy"],
        ["하지만 자꾸 생각나는 맛", "Hajiman jakku saenggangnaneun mat", "But a taste you keep thinking about"],
        ["우리 식당 문은 항상 열려있어", "Uri sikdang muneun hangsang yeollyeoiseo", "Our restaurant door is always open"],
        ["언제든지 와", "Eonjedeunji wa", "Come anytime"],
        ["", "", ""],
        ["God's menu 神메뉴", "God's menu sin menyu", "God's menu, divine menu"],
        ["이건 우리가 만든 거야", "Igeon uriga mandeun geoya", "This is what we made"],
        ["세상 어디서도 못 먹어봤을", "Sesang eodiseo do mot meogeobaosseul", "Something you've never tasted anywhere in the world"],
        ["그런 맛이야", "Geureon masiya", "That's the kind of taste it is"],
      ]),
    },
  });

  const skzMiroh = await prisma.song.upsert({
    where: { slug: "stray-kids-miroh" },
    update: {},
    create: {
      slug: "stray-kids-miroh",
      title: "MIROH",
      albumId: skzAlbum1.id,
      releaseYear: 2019,
      ...lyrics([
        ["나는 어디로 가야 하나", "Naneun eodiro gaya hana", "Where am I supposed to go"],
        ["길이 보이지 않아", "Giri boyiji ana", "I can't see the path"],
        ["미로 속에 갇힌 것만 같아", "Miro sogeul gachincheot man gata", "It feels like I'm trapped in a maze"],
        ["어떻게 빠져나가지", "Eotteoke ppajyeonagaji", "How do I get out"],
        ["", "", ""],
        ["두려워하지 마 넌 할 수 있어", "Duryewohaji ma neon hal su isseo", "Don't be afraid, you can do it"],
        ["실패가 두렵더라도", "Silpaega duryeopteorado", "Even if you're afraid of failure"],
        ["끝까지 포기하지 마", "Kkeutkkaji pogihaji ma", "Don't give up to the very end"],
        ["넌 이미 충분히 빛나고 있어", "Neon imi chungbunhi bitnago isseo", "You're already shining enough"],
        ["", "", ""],
        ["MIROH, 미로 속에서", "MIROH, miro sogeseo", "MIROH, inside the maze"],
        ["길을 찾아가는 거야", "Gireul chajaganeun geoya", "We're finding our way"],
        ["MIROH, 두려움을 넘어", "MIROH, duryeomumeul neomeo", "MIROH, beyond the fear"],
        ["우리는 앞으로 나아가", "Urineun apeuro naaga", "We move forward"],
        ["", "", ""],
        ["틀려도 괜찮아", "Teullyeodo gwaenchana", "It's okay to be wrong"],
        ["완벽하지 않아도 돼", "Wanbyeokhaji anado dwae", "You don't have to be perfect"],
        ["넘어져도 다시 일어나면 돼", "Neomeojyeodo dasi ireonamyeon dwae", "Even if you fall, just get back up"],
        ["그게 바로 용기야", "Geuge baro yonggi ya", "That's what courage is"],
        ["", "", ""],
        ["나는 내 길을 만들어갈 거야", "Naneun nae gireul mandeureogal geoya", "I'll create my own path"],
        ["아무도 가지 않은 길이라도", "Amudo gaji aneun giritarado", "Even if it's a path no one has taken"],
        ["내 발로 직접 걸어가", "Nae ballo jikjeop georeo ga", "I'll walk it with my own feet"],
        ["그게 나의 방식이야", "Geuge naui bangsigiya", "That's my way"],
        ["", "", ""],
        ["MIROH, 미로 속에서", "MIROH, miro sogeseo", "MIROH, inside the maze"],
        ["길을 찾아가는 거야", "Gireul chajaganeun geoya", "We're finding our way"],
        ["MIROH, 두려움을 넘어", "MIROH, duryeomumeul neomeo", "MIROH, beyond the fear"],
        ["우리는 앞으로 나아가", "Urineun apeuro naaga", "We move forward"],
        ["", "", ""],
        ["미로가 끝나는 곳에서", "Miroga kkeutnanneun goseseo", "At the end of the maze"],
        ["우리를 기다리는 건", "Urireul gidarineun geon", "What's waiting for us"],
        ["새로운 세계야", "Saeroun segyeya", "Is a new world"],
        ["두려워하지 마", "Duryewohaji ma", "Don't be afraid"],
      ]),
    },
  });

  const skzThunderous = await prisma.song.upsert({
    where: { slug: "stray-kids-thunderous" },
    update: {},
    create: {
      slug: "stray-kids-thunderous",
      title: "Thunderous (소리꾼)",
      albumId: skzAlbum2.id,
      releaseYear: 2021,
      ...lyrics([
        ["소리꾼이 나타났다", "Sorikkuniga natanatta", "The vocalist has appeared"],
        ["들어봐 이 소리를", "Deureobwa i sorireul", "Listen to this sound"],
        ["천둥소리처럼 울려퍼져", "Cheondungsoricho reom ullyeopyeojyeo", "Echoing like the sound of thunder"],
        ["온 세상을 뒤흔들어", "On sesangeul dwiheundeulleo", "Shaking the whole world"],
        ["", "", ""],
        ["우린 소리꾼 대한민국의 힘", "Urin soriguun daehanmingugui him", "We are vocalists, the strength of Korea"],
        ["판소리의 혼이 담긴", "Pansoriui honi damgin", "Infused with the soul of pansori"],
        ["새로운 노래를 불러", "Saeroun noraereal bulle o", "We sing a new song"],
        ["세상을 깨워라", "Sesangeul kkaewora", "Wake up the world"],
        ["", "", ""],
        ["Thunderous, thunderous", "Thunderous, thunderous", "Thunderous, thunderous"],
        ["우리의 목소리로", "Uriui moksoriro", "With our voices"],
        ["하늘을 찔러라", "Haneureul jilleora", "Pierce the sky"],
        ["Thunderous, thunderous", "Thunderous, thunderous", "Thunderous, thunderous"],
        ["이 소리 들려라", "I sori deullyeora", "Let this sound be heard"],
        ["", "", ""],
        ["전통과 현대가 만나는 곳에서", "Jeontongwa hyeondaega mannaneun goseseo", "Where tradition and modernity meet"],
        ["우리는 새로운 소리를 만들어", "Urineun saeroun sorireul mandeul eo", "We create a new sound"],
        ["두렵지 않아 비판이 있어도", "Duryeopji ana bipani isseodo", "I'm not afraid even if there's criticism"],
        ["이게 우리의 방식이야", "Ige uriui bangsigiya", "This is our way"],
        ["", "", ""],
        ["소리꾼의 노래가 울린다", "Sorikkunui noraega ullinda", "The vocalist's song rings out"],
        ["천지를 뒤흔드는 소리로", "Cheonjireul dwiheundeuneun soriro", "With a sound that shakes heaven and earth"],
        ["우리의 이야기를 들어봐", "Uriui iyagireul deureobwa", "Listen to our story"],
        ["이게 바로 우리야", "Ige baro uriya", "This is exactly who we are"],
        ["", "", ""],
        ["Thunderous, thunderous", "Thunderous, thunderous", "Thunderous, thunderous"],
        ["우리의 목소리로", "Uriui moksoriro", "With our voices"],
        ["하늘을 찔러라", "Haneureul jilleora", "Pierce the sky"],
        ["Thunderous, thunderous", "Thunderous, thunderous", "Thunderous, thunderous"],
        ["이 소리 들려라", "I sori deullyeora", "Let this sound be heard"],
        ["", "", ""],
        ["소리꾼이 나타났다", "Sorikkuniga natanatta", "The vocalist has appeared"],
        ["들어봐 이 소리를", "Deureobwa i sorireul", "Listen to this sound"],
        ["온 세상이 멈추는 순간", "On sesangi meomchuneun sungan", "The moment the whole world stops"],
        ["우리가 노래한다", "Uriga noeaehanda", "We sing"],
      ]),
    },
  });

  const skzCase143 = await prisma.song.upsert({
    where: { slug: "stray-kids-case-143" },
    update: {},
    create: {
      slug: "stray-kids-case-143",
      title: "CASE 143",
      albumId: skzAlbum2.id,
      releaseYear: 2022,
      ...lyrics([
        ["CASE 143, 너를 사랑해", "CASE 143, neoreul saranghae", "CASE 143, I love you"],
        ["이게 무슨 증거냐고", "Ige museun jeunggeonya go", "You ask what evidence this is"],
        ["내 심장이 증거야", "Nae simjangi jeunggeoya", "My heart is the evidence"],
        ["", "", ""],
        ["매일 아침 눈을 뜨면", "Maeil achim nuneul tteumyeon", "Every morning when I open my eyes"],
        ["제일 먼저 네 생각이 나", "Jeil meonjeo ne saenggangi na", "You're the first thing I think of"],
        ["이상한 거 알아, 근데 어떡해", "Isanghan geo ara, geunde eotteokhae", "I know it's strange, but what can I do"],
        ["이게 사랑이래", "Ige sarangirae", "They say this is love"],
        ["", "", ""],
        ["143, 사랑해 사랑해", "143, saranghae saranghae", "143, I love you I love you"],
        ["이 마음 변하지 않을 거야", "I maeum byeonhaji aneul geoya", "These feelings won't change"],
        ["143, 언제나 언제나", "143, eonjena eonjena", "143, always always"],
        ["네 곁에 있을게", "Ne gyeote isseulge", "I'll be by your side"],
        ["", "", ""],
        ["너를 처음 봤을 때 알았어", "Neoreul cheoeum bwasseul ttae arasseo", "I knew when I first saw you"],
        ["이건 뭔가 달라", "Igeon mwonga dalla", "This is something different"],
        ["설명할 수 없는 이 느낌", "Seolmyeonghal su eopneun i neukkkim", "This feeling I can't explain"],
        ["바로 사랑이야", "Baro sarangiya", "Is exactly love"],
        ["", "", ""],
        ["두려워도 말할게", "Duryeowodo malhalge", "Even though I'm scared I'll say it"],
        ["이 마음 숨기지 않을게", "I maeum sumgiji aneulge", "I won't hide these feelings"],
        ["너를 사랑해, 진심으로", "Neoreul saranghae, jinsimeuro", "I love you, sincerely"],
        ["믿어줘, 제발", "Midyeojweo, jebal", "Please believe me"],
        ["", "", ""],
        ["143, 사랑해 사랑해", "143, saranghae saranghae", "143, I love you I love you"],
        ["이 마음 변하지 않을 거야", "I maeum byeonhaji aneul geoya", "These feelings won't change"],
        ["143, 언제나 언제나", "143, eonjena eonjena", "143, always always"],
        ["네 곁에 있을게", "Ne gyeote isseulge", "I'll be by your side"],
        ["", "", ""],
        ["CASE 143, 이건 사랑이야", "CASE 143, igeon sarangiya", "CASE 143, this is love"],
        ["증거가 필요해? 내가 보여줄게", "Jeonggega piryohae? Naega boyeojulge", "Need proof? I'll show you"],
        ["143, 사랑해", "143, saranghae", "143, I love you"],
        ["영원히", "Yeongwonhi", "Forever"],
      ]),
    },
  });

  const skzManiac = await prisma.song.upsert({
    where: { slug: "stray-kids-maniac" },
    update: {},
    create: {
      slug: "stray-kids-maniac",
      title: "Maniac",
      albumId: skzAlbum2.id,
      releaseYear: 2022,
      ...lyrics([
        ["I'm a maniac, maniac", "I'm a maniac, maniac", "I'm a maniac, maniac"],
        ["내가 미쳤다고 해도 괜찮아", "Naega michyeottago haedo gwaenchana", "Even if they say I'm crazy, I'm fine"],
        ["이게 바로 나야", "Ige baro naya", "This is exactly who I am"],
        ["I'm a maniac", "I'm a maniac", "I'm a maniac"],
        ["", "", ""],
        ["남들 눈엔 이상해 보여도", "Namdeul nunae isanghae boyeodo", "Even if I look strange in others' eyes"],
        ["나는 내 방식이 있어", "Naneun nae bangsigi isseo", "I have my own way"],
        ["규칙 같은 거 필요 없어", "Gyuchik gateun geo piryeo eopseo", "I don't need rules"],
        ["내가 만들어가는 세상", "Naega mandeureoganeun sesang", "The world I'm creating"],
        ["", "", ""],
        ["Maniac, maniac, 나는 자유로워", "Maniac, maniac, naneun jayurooe", "Maniac, maniac, I'm free"],
        ["틀에 박힌 생각은 됐어", "Teure bakhin saengageugeun dwaesseo", "I'm done with conventional thinking"],
        ["Maniac, maniac, 내 길을 가", "Maniac, maniac, nae gireul ga", "Maniac, maniac, I walk my path"],
        ["누가 뭐래도 상관없어", "Nuga mwollaedo sanggwaneopseo", "I don't care what anyone says"],
        ["", "", ""],
        ["세상이 나보고 미쳤다 해도", "Sesangi nabogo michyeotta haedo", "Even if the world says I'm crazy"],
        ["나는 신경 쓰지 않아", "Naneun singyeong sseuji ana", "I don't care"],
        ["오히려 더 자유롭게", "Ohiryeo deo jayuropge", "I'd rather be more free"],
        ["내 음악을 해", "Nae eumageul hae", "And make my music"],
        ["", "", ""],
        ["이게 내 정체성이야", "Ige nae jeongcheseongi ya", "This is my identity"],
        ["부끄럽지 않아", "Bukkeureupji ana", "I'm not ashamed"],
        ["나를 있는 그대로 봐줘", "Nareul inneun geudaero bwajweo", "See me as I am"],
        ["그게 전부야", "Geuge jeonbuya", "That's all there is"],
        ["", "", ""],
        ["Maniac, maniac, 나는 자유로워", "Maniac, maniac, naneun jayurooe", "Maniac, maniac, I'm free"],
        ["틀에 박힌 생각은 됐어", "Teure bakhin saengageugeun dwaesseo", "I'm done with conventional thinking"],
        ["Maniac, maniac, 내 길을 가", "Maniac, maniac, nae gireul ga", "Maniac, maniac, I walk my path"],
        ["누가 뭐래도 상관없어", "Nuga mwollaedo sanggwaneopseo", "I don't care what anyone says"],
        ["", "", ""],
        ["I'm a maniac, and I'm proud", "I'm a maniac, and I'm proud", "I'm a maniac, and I'm proud"],
        ["이게 나야, 이게 우리야", "Ige naya, ige uriya", "This is me, this is us"],
        ["I'm a maniac", "I'm a maniac", "I'm a maniac"],
        ["영원히", "Yeongwonhi", "Forever"],
      ]),
    },
  });

  for (const song of [skzGodsMenu, skzMiroh, skzThunderous, skzCase143, skzManiac]) {
    await prisma.songCredit.upsert({
      where: { id: `credit-${song.slug}-stray-kids` },
      update: {},
      create: { id: `credit-${song.slug}-stray-kids`, songId: song.id, artistId: strayKids.id, role: "performer" },
    });
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // TXT (Tomorrow X Together)
  // ═══════════════════════════════════════════════════════════════════════════
  const txt = await prisma.artist.upsert({
    where: { slug: "txt" },
    update: {},
    create: {
      slug: "txt",
      type: "GROUP",
      stageName: "TXT (Tomorrow X Together)",
      debutYear: 2019,
      labelId: hybe.id,
      bio: "Tomorrow X Together (투모로우바이투게더), commonly known as TXT, is a five-member South Korean boy group formed by Big Hit Music (a subsidiary of HYBE), debuting on March 4, 2019. Consisting of Yeonjun, Soobin, Beomgyu, Taehyun, and Huening Kai, TXT explores coming-of-age themes, fantasy, and the anxieties of youth through their music.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/230923_TXT_at_GMA_Strahan%2C_Sara_%26_Keke_cropped.jpg/960px-230923_TXT_at_GMA_Strahan%2C_Sara_%26_Keke_cropped.jpg",
    },
  });

  const txtAlbum1 = await prisma.album.upsert({
    where: { slug: "txt-the-dream-chapter-magic" },
    update: {},
    create: {
      slug: "txt-the-dream-chapter-magic",
      title: "The Dream Chapter: MAGIC",
      artistId: txt.id,
      releaseYear: 2019,
      type: "ALBUM",
      coverArt: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/The_Dream_Chapter-_MAGIC.png/220px-The_Dream_Chapter-_MAGIC.png",
    },
  });

  const txtAlbum2 = await prisma.album.upsert({
    where: { slug: "txt-the-chaos-chapter-freeze" },
    update: {},
    create: {
      slug: "txt-the-chaos-chapter-freeze",
      title: "The Chaos Chapter: FREEZE",
      artistId: txt.id,
      releaseYear: 2021,
      type: "ALBUM",
      coverArt: "https://upload.wikimedia.org/wikipedia/en/thumb/4/40/TXT_The_Chaos_Chapter_FREEZE.png/220px-TXT_The_Chaos_Chapter_FREEZE.png",
    },
  });

  const txtCrown = await prisma.song.upsert({
    where: { slug: "txt-crown" },
    update: {},
    create: {
      slug: "txt-crown",
      title: "Crown (어느날 머리에서 뿔이 자랐다)",
      albumId: txtAlbum1.id,
      releaseYear: 2019,
      ...lyrics([
        ["어느 날 아침 일어났더니", "Eoneu nal achim ireonatteoni", "One morning when I woke up"],
        ["머리에서 뿔이 자랐어", "Meorieseo ppuri jaraosseo", "Horns had grown from my head"],
        ["거울을 보며 생각했어", "Geoureuil bomyeo saengakhaesseo", "Looking in the mirror, I thought"],
        ["이게 뭐가 된 거지", "Ige mwoga doen geoji", "What have I become"],
        ["", "", ""],
        ["두려웠어 사람들이 날 볼까봐", "Duryeowosseo saramdeuri nal bolkkabwa", "I was afraid people would see me"],
        ["이 뿔을 숨기고 싶었어", "I ppureul sumgigo sipeosseo", "I wanted to hide these horns"],
        ["하지만 넌 말했어", "Hajiman neon malhaesseo", "But you said"],
        ["그거 왕관 같아", "Geugeio wanggwan gata", "That looks like a crown"],
        ["", "", ""],
        ["Crown, 나의 왕관이야", "Crown, naui wangwaniya", "Crown, it's my crown"],
        ["두렵지 않아 이제는", "Duryeopji ana ijeneun", "I'm not afraid anymore"],
        ["Crown, 나를 특별하게 만드는", "Crown, nareul teukbyeorhage mandeuneun", "Crown, what makes me special"],
        ["내 뿔을 자랑스러워해", "Nae ppureul jarangseureowohae", "I'm proud of my horns"],
        ["", "", ""],
        ["달랐던 내가 싫었어", "Dallattteon naega silheosseo", "I used to hate that I was different"],
        ["평범하고 싶었어", "Pyeongbeomhago sipeosseo", "I wanted to be ordinary"],
        ["왜 나만 이런 걸까", "Wae naman ireon geolkka", "Why am I the only one like this"],
        ["이유를 몰랐어", "Iyureul mollatsseo", "I didn't know why"],
        ["", "", ""],
        ["하지만 이제 알아", "Hajiman ije ara", "But now I know"],
        ["다름이 아름다움이야", "Dareumi areumdaumiya", "Difference is beauty"],
        ["내 뿔은 약점이 아니야", "Nae ppureun yakjeomi aniya", "My horns aren't a weakness"],
        ["나만의 왕관이야", "Namaneui wangwaniya", "They're my own crown"],
        ["", "", ""],
        ["Crown, 나의 왕관이야", "Crown, naui wangwaniya", "Crown, it's my crown"],
        ["두렵지 않아 이제는", "Duryeopji ana ijeneun", "I'm not afraid anymore"],
        ["Crown, 나를 특별하게 만드는", "Crown, nareul teukbyeorhage mandeuneun", "Crown, what makes me special"],
        ["내 뿔을 자랑스러워해", "Nae ppureul jarangseureowohae", "I'm proud of my horns"],
        ["", "", ""],
        ["어느 날 아침 일어났더니", "Eoneu nal achim ireonatteoni", "One morning when I woke up"],
        ["머리에서 뿔이 자랐어", "Meorieseo ppuri jaraosseo", "Horns had grown from my head"],
        ["이제는 알아, 이건 왕관이야", "Ijeneun ara, igeon wangwaniya", "Now I know, this is a crown"],
        ["나의 자랑스러운 왕관", "Naui jarangseureoun wangwan", "My proud crown"],
      ]),
    },
  });

  const txtLoveSong = await prisma.song.upsert({
    where: { slug: "txt-0x1-lovesong" },
    update: {},
    create: {
      slug: "txt-0x1-lovesong",
      title: "0X1=LOVESONG (I Know I Love You)",
      albumId: txtAlbum2.id,
      releaseYear: 2021,
      ...lyrics([
        ["이상해 이 느낌이", "Isanghae i neukkimi", "Strange, this feeling"],
        ["처음 보는 것들이 눈에 들어와", "Cheoeum boneun geotdeuri nune deureo wa", "Things I've never seen come into my eyes"],
        ["세상이 달라 보여", "Sesangi dalla boyeo", "The world looks different"],
        ["너를 만나고 난 뒤부터", "Neoreul mannago nan dwibeuteo", "Since I met you"],
        ["", "", ""],
        ["0 곱하기 1은 0이지만", "0 gobhagi 1eun 0ijiman", "Zero times one equals zero, but"],
        ["이상하게 내 마음속엔 1이야", "Isanghage nae maeumsogeun 1iya", "Strangely in my heart it's one"],
        ["네가 있으면 0도 1이 돼", "Nega isseumyeon 0do 1i dwae", "When you're there, even zero becomes one"],
        ["이게 사랑의 방정식인가봐", "Ige sarangui bangjeongsigenabwa", "Maybe this is the equation of love"],
        ["", "", ""],
        ["I know I love you", "I know I love you", "I know I love you"],
        ["확신할 수 없어도", "Hwaksinhal su eobeodo", "Even if I can't be certain"],
        ["I know I love you", "I know I love you", "I know I love you"],
        ["이 마음은 진짜야", "I maeeumeun jinjjaya", "These feelings are real"],
        ["", "", ""],
        ["무너지는 세상 속에서도", "Muneojineun sesang sogeseo do", "Even in a crumbling world"],
        ["너만 보여", "Neoman boyeo", "I only see you"],
        ["모든 게 흐릿해질 때도", "Modeun ge heurithaejil ttaedo", "Even when everything gets blurry"],
        ["넌 선명해", "Neon seonmyeonghae", "You're vivid"],
        ["", "", ""],
        ["0 더하기 1은 1이고", "0 deohagi 1eun 1igo", "Zero plus one is one, and"],
        ["1 더하기 너는 전부야", "1 deohagi neoneun jeonbuya", "One plus you is everything"],
        ["이 수식이 말해주는 건", "I susiigi malhaejuneun geon", "What this equation tells me"],
        ["네가 내 전부라는 거야", "Nega nae jeonnburaneun geoya", "Is that you're everything to me"],
        ["", "", ""],
        ["I know I love you", "I know I love you", "I know I love you"],
        ["확신할 수 없어도", "Hwaksinhal su eobeodo", "Even if I can't be certain"],
        ["I know I love you", "I know I love you", "I know I love you"],
        ["이 마음은 진짜야", "I maeeumeun jinjjaya", "These feelings are real"],
        ["", "", ""],
        ["0X1=LOVESONG", "0X1=LOVESONG", "0X1=LOVESONG"],
        ["이게 내 사랑의 공식이야", "Ige nae sarangui gongsigiya", "This is my formula for love"],
        ["너를 사랑해", "Neoreul saranghae", "I love you"],
        ["그걸로 충분해", "Geugeollo chungbunhae", "That's enough"],
      ]),
    },
  });

  const txtBlueHour = await prisma.song.upsert({
    where: { slug: "txt-blue-hour" },
    update: {},
    create: {
      slug: "txt-blue-hour",
      title: "Blue Hour (5시 53분의 하늘에서 발견한 너와 나)",
      albumId: txtAlbum1.id,
      releaseYear: 2020,
      ...lyrics([
        ["5시 53분의 하늘", "5si 53bunui haneul", "The 5:53 sky"],
        ["주황빛으로 물들어가는", "Juhwangbicheu ro muldeureoganeun", "Gradually being dyed orange"],
        ["그 순간을 같이 보고 싶어", "Geu sunganeul gachi bogo sipeo", "I want to watch that moment with you"],
        ["너와 나, 이 자리에서", "Neowa na, i jarieseo", "You and I, right here"],
        ["", "", ""],
        ["하루가 끝나가는 시간", "Haruiga kkeutnanaganeun sigan", "The time when the day ends"],
        ["모든 게 파란색으로 물드는", "Modeun ge paransaegeuro mulduneun", "When everything is dyed blue"],
        ["그 Blue Hour에 네가 보고 싶어", "Geu Blue Hour-ae nega bogo sipeo", "During that Blue Hour I miss you"],
        ["언제나, 항상", "Eonjena, hangsang", "Always, always"],
        ["", "", ""],
        ["Blue Hour, 우리만의 시간", "Blue Hour, urimaneui sigan", "Blue Hour, our time"],
        ["하늘이 주황빛으로 물들 때", "Haneuri juhwangbicheu ro muldeul ttae", "When the sky is dyed orange"],
        ["너와 함께라면 괜찮아", "Neowa hamkkeoranimyeon gwaenchana", "As long as I'm with you, it's fine"],
        ["영원히 이 순간이 계속됐으면", "Yeongwonhi i sungani gyesokdwaesseumyeon", "I wish this moment would last forever"],
        ["", "", ""],
        ["낮과 밤 사이", "Najgwa bam sai", "Between day and night"],
        ["그 찰나의 순간에", "Geu challnaui sungane", "In that fleeting moment"],
        ["세상이 가장 아름다워", "Sesangi gajang areumdaweo", "The world is most beautiful"],
        ["네가 있기 때문에", "Nega itgi ttaemune", "Because you're there"],
        ["", "", ""],
        ["5시 53분, 우리의 시간", "5si 53bun, uriui sigan", "5:53, our time"],
        ["하늘에서 발견한 너와 나", "Haneureseo balgyeonhan neowa na", "You and I discovered in the sky"],
        ["이 순간이 영원하길 바라", "I sungani yeongwonhagil bara", "I hope this moment lasts forever"],
        ["Blue Hour, 사라지지 마", "Blue Hour, sarajiji ma", "Blue Hour, don't disappear"],
        ["", "", ""],
        ["Blue Hour, 우리만의 시간", "Blue Hour, urimaneui sigan", "Blue Hour, our time"],
        ["하늘이 주황빛으로 물들 때", "Haneuri juhwangbicheu ro muldeul ttae", "When the sky is dyed orange"],
        ["너와 함께라면 괜찮아", "Neowa hamkkeoranimyeon gwaenchana", "As long as I'm with you, it's fine"],
        ["영원히 이 순간이 계속됐으면", "Yeongwonhi i sungani gyesokdwaesseumyeon", "I wish this moment would last forever"],
        ["", "", ""],
        ["Blue Hour", "Blue Hour", "Blue Hour"],
        ["이 아름다운 시간", "I areumdaun sigan", "This beautiful time"],
        ["너와 함께", "Neowa hamkke", "With you"],
        ["영원히", "Yeongwonhi", "Forever"],
      ]),
    },
  });

  const txtGoodBoyGoneBad = await prisma.song.upsert({
    where: { slug: "txt-good-boy-gone-bad" },
    update: {},
    create: {
      slug: "txt-good-boy-gone-bad",
      title: "Good Boy Gone Bad",
      albumId: txtAlbum2.id,
      releaseYear: 2022,
      ...lyrics([
        ["착한 애였는데", "Chacan aeyeonneunde", "I used to be a good boy"],
        ["언제부터 이렇게 됐을까", "Eonjebuteo ireoke dwaesseulkka", "When did I become like this"],
        ["다 너 때문이야", "Da neo ttaemuniya", "It's all because of you"],
        ["이렇게 변해버렸어", "Ireoke byeonhaebeolyeosseo", "I've changed like this"],
        ["", "", ""],
        ["한때는 착하게만 살았는데", "Hanttaeneun chakagemanago saratneunde", "There was a time I only lived nicely"],
        ["웃음이 많은 아이였는데", "Useumi maneun aiyeotnunde", "I was a child who smiled a lot"],
        ["근데 넌 내 마음을 부숴놨어", "Geunde neon nae maeumeul busyeonwasseo", "But you broke my heart"],
        ["이제 난 달라졌어", "Ije nan dalajyeosseo", "Now I've changed"],
        ["", "", ""],
        ["Good boy gone bad", "Good boy gone bad", "Good boy gone bad"],
        ["이제 나는 달라", "Ije naneun dalla", "Now I'm different"],
        ["Good boy gone bad", "Good boy gone bad", "Good boy gone bad"],
        ["돌아갈 수 없어", "Doragal su eopseo", "I can't go back"],
        ["", "", ""],
        ["웃음을 잃어버렸어", "Useoumeul ileobeoryeosseo", "I lost my smile"],
        ["눈물도 말라버렸어", "Nunmuldo mallabeoryeosseo", "My tears dried up too"],
        ["감정이 사라져가고 있어", "Gamjeungi sarajyeogago isseo", "My emotions are disappearing"],
        ["이게 다 너 때문이야", "Ige da neo ttaemuniya", "This is all because of you"],
        ["", "", ""],
        ["한 번쯤 나를 봐줬으면", "Han beonjjeum nareul bwajwosseumyeon", "I wish you'd looked at me at least once"],
        ["내 마음을 알아줬으면", "Nae maeeumeul arajwosseumyeon", "I wish you'd understood my feelings"],
        ["하지만 넌 몰랐어", "Hajiman neon mollasseo", "But you didn't know"],
        ["아니면 알면서 무시했어", "Animyeon almyeonseo musihaeosseo", "Or maybe you knew and ignored it"],
        ["", "", ""],
        ["Good boy gone bad", "Good boy gone bad", "Good boy gone bad"],
        ["이제 나는 달라", "Ije naneun dalla", "Now I'm different"],
        ["Good boy gone bad", "Good boy gone bad", "Good boy gone bad"],
        ["돌아갈 수 없어", "Doragal su eopseo", "I can't go back"],
        ["", "", ""],
        ["착한 애였던 나는 어디 갔나", "Chakcan aeyeotteon naneun eodi gatna", "Where did the good boy I used to be go"],
        ["이제 남은 건 상처뿐이야", "Ije nameun geon sangcheoppuniya", "Now all that's left is wounds"],
        ["Good boy gone bad", "Good boy gone bad", "Good boy gone bad"],
        ["이게 다 너 때문이야", "Ige da neo ttaemuniya", "This is all because of you"],
      ]),
    },
  });

  for (const song of [txtCrown, txtLoveSong, txtBlueHour, txtGoodBoyGoneBad]) {
    await prisma.songCredit.upsert({
      where: { id: `credit-${song.slug}-txt` },
      update: {},
      create: { id: `credit-${song.slug}-txt`, songId: song.id, artistId: txt.id, role: "performer" },
    });
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // ENHYPEN
  // ═══════════════════════════════════════════════════════════════════════════
  const enhypen = await prisma.artist.upsert({
    where: { slug: "enhypen" },
    update: {},
    create: {
      slug: "enhypen",
      type: "GROUP",
      stageName: "ENHYPEN",
      debutYear: 2020,
      labelId: hybe.id,
      bio: "ENHYPEN (엔하이픈) is a seven-member South Korean-Japanese boy group formed through the reality competition show I-Land, produced by Big Hit Entertainment and CJ ENM. The group debuted on November 30, 2020 under BELIFT LAB. Consisting of Jungwon, Heeseung, Jay, Jake, Sunghoon, Sunoo, and Ni-ki, ENHYPEN is known for their vampire-inspired debut concept and dark, cinematic storytelling.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/ENHYPEN_in_2022_%28cropped%29.jpg/960px-ENHYPEN_in_2022_%28cropped%29.jpg",
    },
  });

  const enAlbum1 = await prisma.album.upsert({
    where: { slug: "enhypen-border-day-one" },
    update: {},
    create: {
      slug: "enhypen-border-day-one",
      title: "BORDER: DAY ONE",
      artistId: enhypen.id,
      releaseYear: 2020,
      type: "ALBUM",
      coverArt: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c8/ENHYPEN_-_Border_Day_One.png/220px-ENHYPEN_-_Border_Day_One.png",
    },
  });

  const enAlbum2 = await prisma.album.upsert({
    where: { slug: "enhypen-dimension-dilemma" },
    update: {},
    create: {
      slug: "enhypen-dimension-dilemma",
      title: "DIMENSION : DILEMMA",
      artistId: enhypen.id,
      releaseYear: 2021,
      type: "ALBUM",
      coverArt: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/ENHYPEN_-_Dimension_Dilemma.png/220px-ENHYPEN_-_Dimension_Dilemma.png",
    },
  });

  const enGivenTaken = await prisma.song.upsert({
    where: { slug: "enhypen-given-taken" },
    update: {},
    create: {
      slug: "enhypen-given-taken",
      title: "Given-Taken",
      albumId: enAlbum1.id,
      releaseYear: 2020,
      ...lyrics([
        ["주어진 것들 속에서", "Jueojin geotdeul sogeseo", "Among the things given"],
        ["내가 선택할 수 있는 건", "Naega seontaekhal su inneun geon", "What I can choose"],
        ["그리 많지 않았어", "Geuri manchi anasseo", "Wasn't that much"],
        ["그래도 나는 여기 있어", "Geuraedo naneun yeogi isseo", "Still, I'm here"],
        ["", "", ""],
        ["처음 만나는 세상에서", "Cheoeum mannaneun sesangeseo", "In a world I'm meeting for the first time"],
        ["모든 게 낯설고 두려워도", "Modeun ge natsseolgo duryeowodo", "Even though everything is unfamiliar and scary"],
        ["내 손을 잡아줄 사람", "Nae soneul jabajul saram", "Someone who will hold my hand"],
        ["네가 있어서 괜찮아", "Nega isseoseo gwaenchana", "It's okay because you're there"],
        ["", "", ""],
        ["Given, taken 우리가 만난 건", "Given, taken uriga mannan geon", "Given, taken, the fact that we met"],
        ["운명이었던 걸까", "Unmyeongieootteon geolkka", "Was it fate"],
        ["Given, taken 이 감정들이", "Given, taken i gamjeongdeuri", "Given, taken, these feelings"],
        ["진짜인 걸 알아", "Jinjjagin geol ara", "I know are real"],
        ["", "", ""],
        ["두려워도 괜찮아", "Duryeowodo gwaenchana", "It's okay to be scared"],
        ["새로운 시작이니까", "Saeroun sijaginiikka", "Because it's a new beginning"],
        ["함께라면 어디든 갈 수 있어", "Hamkkeoranimyeon eodideun gal su isseo", "Together we can go anywhere"],
        ["너와 나", "Neowa na", "You and I"],
        ["", "", ""],
        ["주어진 것들 속에서", "Jueojin geotdeul sogeseo", "Among the things given"],
        ["내가 고른 건 너야", "Naega goreun geon neoya", "What I chose is you"],
        ["수많은 것들 중에서도", "Sumaneun geotdeul jungeseo do", "Among so many things"],
        ["오직 너만이야", "Ojik neomaneiya", "It's only you"],
        ["", "", ""],
        ["Given, taken 우리가 만난 건", "Given, taken uriga mannan geon", "Given, taken, the fact that we met"],
        ["운명이었던 걸까", "Unmyeongieootteon geolkka", "Was it fate"],
        ["Given, taken 이 감정들이", "Given, taken i gamjeongdeuri", "Given, taken, these feelings"],
        ["진짜인 걸 알아", "Jinjjagin geol ara", "I know are real"],
        ["", "", ""],
        ["Given or taken", "Given or taken", "Given or taken"],
        ["어느 쪽이든 괜찮아", "Eoneu jjogigeun gwaenchana", "Either way is fine"],
        ["네가 있으면 돼", "Nega isseumyeon dwae", "As long as you're there"],
        ["그걸로 충분해", "Geugeollo chungbunhae", "That's enough"],
      ]),
    },
  });

  const enDrunkDazed = await prisma.song.upsert({
    where: { slug: "enhypen-drunk-dazed" },
    update: {},
    create: {
      slug: "enhypen-drunk-dazed",
      title: "Drunk-Dazed",
      albumId: enAlbum2.id,
      releaseYear: 2021,
      ...lyrics([
        ["취해버렸어 완전히", "Chwihaebeoryeosseo wanjeonhi", "I'm completely drunk"],
        ["네 눈빛에 빠져들어", "Ne nunbiche ppajyeodeulleo", "Falling into your gaze"],
        ["정신이 하나도 없어", "Jeongsini hanado eopseo", "I'm completely out of my mind"],
        ["이게 현실인지 꿈인지", "Ige hyeonsilanji kkumlanji", "Whether this is reality or a dream"],
        ["", "", ""],
        ["Drunk-dazed, 너 때문에", "Drunk-dazed, neo ttaemune", "Drunk-dazed, because of you"],
        ["아무것도 보이지 않아", "Amugosdo boyiji ana", "I can't see anything"],
        ["Drunk-dazed, 취해버렸어", "Drunk-dazed, chwihaebeoryeosseo", "Drunk-dazed, I've gotten drunk"],
        ["네 매력에 빠져서", "Ne maeryeoge ppajyeoseo", "Falling for your charm"],
        ["", "", ""],
        ["파티가 끝나도 난", "Patiga kkeutnado nan", "Even after the party ends"],
        ["네 생각뿐이야", "Ne saenggakppuniya", "I only think of you"],
        ["이 느낌이 뭔지 몰라도", "I neukkimi mwonji mollado", "Even if I don't know what this feeling is"],
        ["좋아, 계속 좋아", "Joa, gyesok joa", "I like it, I keep liking it"],
        ["", "", ""],
        ["취기가 오르는 것처럼", "Chwigiga oreuneun geotcheoreom", "Like intoxication rising"],
        ["네가 내 안에 퍼져가", "Nega nae ane pyeojyeoga", "You're spreading inside me"],
        ["정신을 차릴 수가 없어", "Jeongsineul charil suga eopseo", "I can't come to my senses"],
        ["계속 취해있고 싶어", "Gyesok chwihaeissgo sipeo", "I want to stay drunk like this"],
        ["", "", ""],
        ["Drunk-dazed, 너 때문에", "Drunk-dazed, neo ttaemune", "Drunk-dazed, because of you"],
        ["아무것도 보이지 않아", "Amugosdo boyiji ana", "I can't see anything"],
        ["Drunk-dazed, 취해버렸어", "Drunk-dazed, chwihaebeoryeosseo", "Drunk-dazed, I've gotten drunk"],
        ["네 매력에 빠져서", "Ne maeryeoge ppajyeoseo", "Falling for your charm"],
        ["", "", ""],
        ["이게 사랑인가봐", "Ige saranginabwa", "I guess this must be love"],
        ["이렇게 취하는 거잖아", "Ireoke chwihaneun geojanha", "Getting drunk like this"],
        ["Drunk-dazed", "Drunk-dazed", "Drunk-dazed"],
        ["너에게 취해버렸어", "Neoege chwihaebeoryeosseo", "I've gotten drunk on you"],
        ["", "", ""],
        ["돌아갈 수 없어 이제는", "Doragal su eopseo ijeneun", "I can't go back now"],
        ["네 세계에 갇혀버렸어", "Ne segyeae gachyeobeoryeosseo", "I'm trapped in your world"],
        ["Drunk-dazed, drunk-dazed", "Drunk-dazed, drunk-dazed", "Drunk-dazed, drunk-dazed"],
        ["영원히 이대로", "Yeongwonhi idaero", "Like this forever"],
      ]),
    },
  });

  const enBiteMe = await prisma.song.upsert({
    where: { slug: "enhypen-bite-me" },
    update: {},
    create: {
      slug: "enhypen-bite-me",
      title: "Bite Me",
      albumId: enAlbum2.id,
      releaseYear: 2023,
      ...lyrics([
        ["Bite me, 날 봐 두려워 마", "Bite me, nal bwa duryeowo ma", "Bite me, look at me, don't be afraid"],
        ["내 세계로 들어와", "Nae segyero deureo wa", "Come into my world"],
        ["너를 기다렸어 오랫동안", "Neoreul gidaryeosseo oraedongan", "I've been waiting for you for so long"],
        ["이제야 나타났어", "Ijeya natanasseo", "You've finally appeared"],
        ["", "", ""],
        ["어둠 속에서 빛나는 너", "Eodeum sogeseo bitnaneun neo", "You shining in the darkness"],
        ["내 눈을 사로잡아", "Nae nuneul sarojaba", "Captivating my eyes"],
        ["운명처럼 느껴지는 이 순간", "Unmyeongcheoreom neukkeyojineun i sungan", "This moment that feels like fate"],
        ["놓치고 싶지 않아", "Nochigo sipji ana", "I don't want to miss it"],
        ["", "", ""],
        ["Bite me, 내 심장을 건드려", "Bite me, nae simjangeul geondeuryeo", "Bite me, touch my heart"],
        ["이 감각을 깨워줘", "I gamgageul kkaewojweo", "Wake up this sensation"],
        ["Bite me, 더 가까이 와줘", "Bite me, deo gakkai wajweo", "Bite me, come closer to me"],
        ["두렵지 않아 이제는", "Duryeopji ana ijeneun", "I'm not afraid anymore"],
        ["", "", ""],
        ["뱀파이어처럼 날 물어", "Baempaieorocheoreom nal mureo", "Bite me like a vampire"],
        ["이 순간을 영원히 새겨줘", "I sunganeul yeongwonhi saegyeojweo", "Engrave this moment forever"],
        ["너에게 모든 걸 줄게", "Neoege modeun geol julge", "I'll give you everything"],
        ["그게 두렵지 않아", "Geuge duryeopji ana", "I'm not afraid of that"],
        ["", "", ""],
        ["어둠과 빛 사이에서", "Eodumgwa bit saieseo", "Between darkness and light"],
        ["우리는 만났어", "Urineun mannasseo", "We met"],
        ["이 경계선 위에서", "I gyeonggyeseon wieseo", "On this borderline"],
        ["사랑을 시작해", "Sarangeul sijakae", "We begin our love"],
        ["", "", ""],
        ["Bite me, 내 심장을 건드려", "Bite me, nae simjangeul geondeuryeo", "Bite me, touch my heart"],
        ["이 감각을 깨워줘", "I gamgageul kkaewojweo", "Wake up this sensation"],
        ["Bite me, 더 가까이 와줘", "Bite me, deo gakkai wajweo", "Bite me, come closer to me"],
        ["두렵지 않아 이제는", "Duryeopji ana ijeneun", "I'm not afraid anymore"],
        ["", "", ""],
        ["Bite me, bite me", "Bite me, bite me", "Bite me, bite me"],
        ["이게 우리의 시작이야", "Ige uriui sijagiya", "This is our beginning"],
        ["어둠 속에서 피어난 사랑", "Eodeum sogeseo pieonan sarang", "Love that bloomed in the darkness"],
        ["영원히", "Yeongwonhi", "Forever"],
      ]),
    },
  });

  const enFuturePerfect = await prisma.song.upsert({
    where: { slug: "enhypen-future-perfect" },
    update: {},
    create: {
      slug: "enhypen-future-perfect",
      title: "Future Perfect (Pass the MIC)",
      albumId: enAlbum2.id,
      releaseYear: 2022,
      ...lyrics([
        ["Pass the MIC, 우리에게 넘겨줘", "Pass the MIC, uriegae neomgyeojweo", "Pass the MIC, hand it over to us"],
        ["이제 우리 차례야", "Ije uri chareyeya", "Now it's our turn"],
        ["세상이 지켜봐도 괜찮아", "Sesangi jikyeobwado gwaenchana", "Even if the world is watching, we're fine"],
        ["우리는 준비됐어", "Urineun junbidwaesseo", "We're ready"],
        ["", "", ""],
        ["완벽한 미래를 향해서", "Wanbyeokhan miraereal hyanghaeseo", "Heading towards a perfect future"],
        ["한 걸음씩 나아가", "Han georeumssik naaga", "Moving forward step by step"],
        ["Future perfect, 이게 우리야", "Future perfect, ige uriya", "Future perfect, this is us"],
        ["멈추지 않을 거야", "Meomchuji aneul geoya", "We won't stop"],
        ["", "", ""],
        ["무대 위에 올라서서", "Mudae wie ollaseoseo", "Standing on stage"],
        ["세상을 향해 외쳐", "Sesangeul hyangha oeachyeo", "We shout to the world"],
        ["이게 우리의 목소리야", "Ige uriui moksoriya", "This is our voice"],
        ["들어봐, 들려줄게", "Deureobwa, deullyeojulge", "Listen, we'll let you hear it"],
        ["", "", ""],
        ["Pass the MIC, 우리가 노래해", "Pass the MIC, uriga noraeahae", "Pass the MIC, we'll sing"],
        ["이 세상에 울려퍼지게", "I sesange ullyeopjyeojige", "So it echoes throughout this world"],
        ["Future perfect, 함께 만들어가는", "Future perfect, hamkke mandeureo ganeun", "Future perfect, creating together"],
        ["우리만의 이야기", "Urimaneui iyagi", "Our own story"],
        ["", "", ""],
        ["두려움은 접어두고", "Duryeoumeun jeobeodogo", "Setting fear aside"],
        ["앞만 보고 달려가", "Apman bogo dallyeoga", "Looking only forward, we run"],
        ["우리의 미래는 밝아", "Uriui miraereal balga", "Our future is bright"],
        ["그걸 믿어", "Geugeollo midyeo", "Believe that"],
        ["", "", ""],
        ["Pass the MIC, 우리에게 넘겨줘", "Pass the MIC, uriegae neomgyeojweo", "Pass the MIC, hand it over to us"],
        ["이제 우리 차례야", "Ije uri chareyeya", "Now it's our turn"],
        ["세상이 지켜봐도 괜찮아", "Sesangi jikyeobwado gwaenchana", "Even if the world is watching, we're fine"],
        ["우리는 준비됐어", "Urineun junbidwaesseo", "We're ready"],
        ["", "", ""],
        ["Future perfect", "Future perfect", "Future perfect"],
        ["이게 우리의 이야기야", "Ige uriui iyagiya", "This is our story"],
        ["Pass the MIC", "Pass the MIC", "Pass the MIC"],
        ["세상아 들어라", "Sesanga deureora", "World, listen"],
      ]),
    },
  });

  for (const song of [enGivenTaken, enDrunkDazed, enBiteMe, enFuturePerfect]) {
    await prisma.songCredit.upsert({
      where: { id: `credit-${song.slug}-enhypen` },
      update: {},
      create: { id: `credit-${song.slug}-enhypen`, songId: song.id, artistId: enhypen.id, role: "performer" },
    });
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // LE SSERAFIM
  // ═══════════════════════════════════════════════════════════════════════════
  const lesserafim = await prisma.artist.upsert({
    where: { slug: "le-sserafim" },
    update: {},
    create: {
      slug: "le-sserafim",
      type: "GROUP",
      stageName: "LE SSERAFIM",
      debutYear: 2022,
      labelId: hybe.id,
      bio: "LE SSERAFIM (르세라핌) is a five-member South Korean girl group formed by Source Music (a subsidiary of HYBE), debuting on May 2, 2022. Consisting of Sakura, Kim Chaewon, Huh Yunjin, Kazuha, and Hong Eunchae, the group's name is an anagram of 'I'M FEARLESS'. They are known for their powerful, confident concept and athletic-inspired choreography.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/LE_SSERAFIM_at_2022_MAMA_Awards.jpg/960px-LE_SSERAFIM_at_2022_MAMA_Awards.jpg",
    },
  });

  const lsAlbum1 = await prisma.album.upsert({
    where: { slug: "le-sserafim-fearless" },
    update: {},
    create: {
      slug: "le-sserafim-fearless",
      title: "FEARLESS",
      artistId: lesserafim.id,
      releaseYear: 2022,
      type: "ALBUM",
      coverArt: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0d/LE_SSERAFIM_-_Fearless.png/220px-LE_SSERAFIM_-_Fearless.png",
    },
  });

  const lsAlbum2 = await prisma.album.upsert({
    where: { slug: "le-sserafim-antifragile" },
    update: {},
    create: {
      slug: "le-sserafim-antifragile",
      title: "ANTIFRAGILE",
      artistId: lesserafim.id,
      releaseYear: 2022,
      type: "ALBUM",
      coverArt: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/LE_SSERAFIM_-_Antifragile.png/220px-LE_SSERAFIM_-_Antifragile.png",
    },
  });

  const lsFearless = await prisma.song.upsert({
    where: { slug: "le-sserafim-fearless" },
    update: {},
    create: {
      slug: "le-sserafim-fearless",
      title: "FEARLESS",
      albumId: lsAlbum1.id,
      releaseYear: 2022,
      ...lyrics([
        ["두렵지 않아 이 세상이", "Duryeopji ana i sesangi", "I'm not afraid of this world"],
        ["내 앞에 무엇이 있어도", "Nae apae mueosi isseodo", "No matter what stands before me"],
        ["당당하게 마주 볼 거야", "Dangdanghage maju bol geoya", "I'll face it head-on with confidence"],
        ["나는 Fearless", "Naneun Fearless", "I am Fearless"],
        ["", "", ""],
        ["남들의 시선이 두려웠던 날들", "Namdeului sisyeoni duryeowotteon naldeul", "Days when I was afraid of others' gazes"],
        ["이제는 그런 거 필요 없어", "Ijeneun geureon geo piryeo eopseo", "I don't need that anymore"],
        ["내 길을 가겠어", "Nae gireul gagetsseo", "I'll go my own way"],
        ["어떤 말도 날 막을 수 없어", "Eotteon maldo nal mageul su eopseo", "No words can stop me"],
        ["", "", ""],
        ["Fearless, fearless", "Fearless, fearless", "Fearless, fearless"],
        ["이게 바로 나야", "Ige baro naya", "This is exactly who I am"],
        ["Fearless, fearless", "Fearless, fearless", "Fearless, fearless"],
        ["두려움 없이 나아가", "Duryeoum eopssi naaga", "Moving forward without fear"],
        ["", "", ""],
        ["실패해도 괜찮아", "Silpaehaedo gwaenchana", "It's okay to fail"],
        ["다시 일어나면 돼", "Dasi ireonamyeon dwae", "Just get back up"],
        ["넘어져도 무릎을 털고", "Neomeojyeodo mureupeul teolgo", "Even if I fall, brushing off my knees"],
        ["계속 걸어가겠어", "Gyesok georeogagetsseo", "I'll keep walking"],
        ["", "", ""],
        ["세상이 뭐라 해도", "Sesangi mwora haedo", "No matter what the world says"],
        ["나는 나야 변하지 않아", "Naneun naya byeonhaji ana", "I am me, I won't change"],
        ["이 확신 하나로", "I hwaksin hanaro", "With this one conviction"],
        ["앞으로 나아가", "Apeuro naaga", "I move forward"],
        ["", "", ""],
        ["Fearless, fearless", "Fearless, fearless", "Fearless, fearless"],
        ["이게 바로 나야", "Ige baro naya", "This is exactly who I am"],
        ["Fearless, fearless", "Fearless, fearless", "Fearless, fearless"],
        ["두려움 없이 나아가", "Duryeoum eopssi naaga", "Moving forward without fear"],
        ["", "", ""],
        ["나는 Fearless", "Naneun Fearless", "I am Fearless"],
        ["이 세상 어디서도", "I sesang eodiseo do", "Anywhere in this world"],
        ["당당하게 서 있을게", "Dangdanghage seo isseulge", "I'll stand tall with confidence"],
        ["그게 르세라핌이야", "Geuge Leuserapimiya", "That's LE SSERAFIM"],
      ]),
    },
  });

  const lsAntifragile = await prisma.song.upsert({
    where: { slug: "le-sserafim-antifragile" },
    update: {},
    create: {
      slug: "le-sserafim-antifragile",
      title: "ANTIFRAGILE",
      albumId: lsAlbum2.id,
      releaseYear: 2022,
      ...lyrics([
        ["부서질수록 강해지는", "Buseojilsurok ganghaeji neun", "The more I break, the stronger I become"],
        ["그게 바로 나야", "Geuge baro naya", "That's exactly who I am"],
        ["Antifragile, antifragile", "Antifragile, antifragile", "Antifragile, antifragile"],
        ["상처가 나를 키워", "Sangcheoga nareul kiwo", "Wounds make me grow"],
        ["", "", ""],
        ["흔들리는 바람 속에서도", "Heundeullineun baram sogeseo do", "Even in the shaking wind"],
        ["뿌리는 더 깊어져가고", "Ppurineun deo gipeojyeogago", "Roots grow even deeper"],
        ["역경이 클수록", "Yeokgyeongi keulsurok", "The greater the adversity"],
        ["더 강해지는 나", "Deo ganghaeji neun na", "The stronger I become"],
        ["", "", ""],
        ["Antifragile, 이게 나야", "Antifragile, ige naya", "Antifragile, this is me"],
        ["상처로 단련된 나야", "Sangcheoro dallyeondoen naya", "I've been tempered by wounds"],
        ["Antifragile, 부숴봐", "Antifragile, busyeobwa", "Antifragile, try to break me"],
        ["오히려 강해질 뿐이야", "Ohiryeo ganghaeji jil ppuniya", "I'll only get stronger"],
        ["", "", ""],
        ["두려움도 내 양식이야", "Duryeoumdo nae yangsigiya", "Even fear is my nourishment"],
        ["실패도 내 성장이야", "Silpaedo nae seongjangiya", "Even failure is my growth"],
        ["이 모든 경험들이", "I modeun gyeongheomdeuri", "All these experiences"],
        ["나를 더 강하게 만들어", "Nareul deo ganghage mandeureo", "Make me stronger"],
        ["", "", ""],
        ["흔들려도 괜찮아", "Heundeullyeodo gwaenchana", "It's okay to be shaken"],
        ["그게 나를 강하게 해", "Geuge nareul ganghage hae", "That's what makes me strong"],
        ["넘어져도 괜찮아", "Neomeojyeodo gwaenchana", "It's okay to fall"],
        ["다시 일어서면 돼", "Dasi ireoseo myeon dwae", "Just stand back up"],
        ["", "", ""],
        ["Antifragile, 이게 나야", "Antifragile, ige naya", "Antifragile, this is me"],
        ["상처로 단련된 나야", "Sangcheoro dallyeondoen naya", "I've been tempered by wounds"],
        ["Antifragile, 부숴봐", "Antifragile, busyeobwa", "Antifragile, try to break me"],
        ["오히려 강해질 뿐이야", "Ohiryeo ganghaeji jil ppuniya", "I'll only get stronger"],
        ["", "", ""],
        ["부서질수록 강해지는", "Buseojilsurok ganghaeji neun", "The more I break, the stronger I become"],
        ["Antifragile", "Antifragile", "Antifragile"],
        ["이게 바로 나야", "Ige baro naya", "This is exactly who I am"],
        ["두려움 없이", "Duryeoum eopssi", "Without fear"],
      ]),
    },
  });

  const lsEvePsyche = await prisma.song.upsert({
    where: { slug: "le-sserafim-eve-psyche" },
    update: {},
    create: {
      slug: "le-sserafim-eve-psyche",
      title: "Eve, Psyche & The Bluebeard's Wife (이브, 프시케 그리고 푸른 수염의 아내)",
      albumId: lsAlbum2.id,
      releaseYear: 2022,
      ...lyrics([
        ["금지된 방문 앞에서", "Geumjidoen bangmun apeseo", "Before a forbidden door"],
        ["두근거리는 내 심장", "Dugeungeorineun nae simjang", "My pounding heart"],
        ["열지 말라고 했잖아", "Yeolji mallago haetjanha", "They said don't open it"],
        ["근데 왜 이리 궁금한 건지", "Geunde wae iri gunggumhan geonji", "But why am I so curious"],
        ["", "", ""],
        ["이브처럼, 프시케처럼", "Ibeu cheoreom, peusike cheoreom", "Like Eve, like Psyche"],
        ["금지된 것에 이끌려", "Geumjidoen geose ikkeullyeo", "Drawn to what's forbidden"],
        ["알면 안 된다는 걸 알면서도", "Almyeon an doenraneun geol almyeon seo do", "Even knowing I shouldn't know"],
        ["손이 가는 걸 어떡해", "Soni ganeun geol eotteokhae", "What can I do when my hand reaches out"],
        ["", "", ""],
        ["푸른 수염의 아내처럼", "Pureun suyeomui anae cheoreom", "Like Bluebeard's wife"],
        ["호기심이 날 이끌어", "Hogiimi nal ikkeulleo", "Curiosity leads me"],
        ["알고 싶어 더 알고 싶어", "Algo sipeo deo algo sipeo", "I want to know, I want to know more"],
        ["열어봐야 알 수 있잖아", "Yeoreobwaya al su itjanha", "I have to open it to know"],
        ["", "", ""],
        ["금지라는 게 더 끌리게 해", "Geumjiraneun ge deo kkeullrige hae", "Being forbidden makes it more enticing"],
        ["이게 인간의 본능인 걸까", "Ige inganui bonneungin geolkka", "Is this human instinct"],
        ["알면 다칠 수 있다는 걸 알아도", "Almyeon dachil su itdaneun geol arado", "Even knowing it might hurt me to know"],
        ["궁금한 걸 어떡해", "Gunggumhan geol eotteokhae", "What can I do when I'm so curious"],
        ["", "", ""],
        ["이브, 프시케, 푸른 수염의 아내", "Ibeu, peusike, pureun suyeomui anae", "Eve, Psyche, Bluebeard's wife"],
        ["우리는 모두 같아", "Urineun modu gata", "We're all the same"],
        ["금지된 것에 이끌리는", "Geumjidoen geose ikkeullineun", "Drawn to the forbidden"],
        ["그 본능을 어떡해", "Geu bonneungeul eotteokhae", "What can we do about that instinct"],
        ["", "", ""],
        ["열어봤어 결국엔", "Yeoreobwasseo gyeolgugen", "I opened it in the end"],
        ["후회해? 아니 오히려", "Huhoeahae? Ani ohiryeo", "Do I regret it? No, rather"],
        ["더 알고 싶어졌어", "Deo algo sipyeojyeosseo", "I want to know even more"],
        ["이게 바로 나야", "Ige baro naya", "This is exactly who I am"],
        ["", "", ""],
        ["금지된 방문 앞에서", "Geumjidoen bangmun apeseo", "Before a forbidden door"],
        ["나는 또 서 있어", "Naneun tto seo isseo", "I'm standing there again"],
        ["이브처럼, 프시케처럼", "Ibeu cheoreom, peusike cheoreom", "Like Eve, like Psyche"],
        ["열어볼 거야", "Yeorebol geoya", "I'm going to open it"],
      ]),
    },
  });

  const lsUnforgiven = await prisma.song.upsert({
    where: { slug: "le-sserafim-unforgiven" },
    update: {},
    create: {
      slug: "le-sserafim-unforgiven",
      title: "UNFORGIVEN (feat. Nile Rodgers)",
      albumId: lsAlbum2.id,
      releaseYear: 2023,
      ...lyrics([
        ["용서받지 못한 자", "Yongseobatnaji motan ja", "One who cannot be forgiven"],
        ["그게 바로 나야", "Geuge baro naya", "That's exactly who I am"],
        ["하지만 난 상관없어", "Hajiman nan sanggwaneopseo", "But I don't care"],
        ["내 방식대로 살아가겠어", "Nae bangsikdaero saraagagetsseo", "I'll live life my own way"],
        ["", "", ""],
        ["세상이 날 욕해도", "Sesangi nal yokhacdo", "Even if the world condemns me"],
        ["내 귀엔 안 들려", "Nae gwiena an deullyeo", "I don't hear it"],
        ["내가 옳다고 믿는 것만", "Naega oltago midneun geotman", "Only what I believe to be right"],
        ["따를 거야", "Ttareul geoya", "I'll follow"],
        ["", "", ""],
        ["Unforgiven, 용서 따윈 필요 없어", "Unforgiven, yongseo ttawien piryeo eopseo", "Unforgiven, I don't need forgiveness"],
        ["내가 원하는 대로 살 거야", "Naega wonhaneun daero sal geoya", "I'll live the way I want"],
        ["Unforgiven, 비판이 무서워?", "Unforgiven, bipani museoowo?", "Unforgiven, afraid of criticism?"],
        ["천만에, 난 Fearless", "Cheonmane, nan Fearless", "Not at all, I'm Fearless"],
        ["", "", ""],
        ["규칙을 어기는 것도", "Gyuchikkeul eogineun geotdo", "Even breaking the rules"],
        ["때론 용기가 필요해", "Ttaeron yonggiga piryeohae", "Sometimes takes courage"],
        ["나는 그 용기를 갖고 있어", "Naneun geu yonggireul gatgo isseo", "I have that courage"],
        ["그게 나의 힘이야", "Geuge naui himiya", "That's my strength"],
        ["", "", ""],
        ["사회가 정한 틀을 벗어나", "Sahyega jeongeun tteurul beoseoona", "Breaking free from society's mold"],
        ["내 길을 만들어가겠어", "Nae gireul mandeureogagetsseo", "I'll forge my own path"],
        ["남들이 뭐라 해도", "Namdeuri mwora haedo", "No matter what others say"],
        ["나는 나야", "Naneun naya", "I am me"],
        ["", "", ""],
        ["Unforgiven, 용서 따윈 필요 없어", "Unforgiven, yongseo ttawien piryeo eopseo", "Unforgiven, I don't need forgiveness"],
        ["내가 원하는 대로 살 거야", "Naega wonhaneun daero sal geoya", "I'll live the way I want"],
        ["Unforgiven, 비판이 무서워?", "Unforgiven, bipani museoowo?", "Unforgiven, afraid of criticism?"],
        ["천만에, 난 Fearless", "Cheonmane, nan Fearless", "Not at all, I'm Fearless"],
        ["", "", ""],
        ["용서받지 못해도 괜찮아", "Yongseobatnaji mothaedo gwaenchana", "Even if I can't be forgiven, it's fine"],
        ["내 신념대로 살았으니까", "Nae sinnyeomdaero sarasseoniikka", "Because I lived by my own conviction"],
        ["Unforgiven", "Unforgiven", "Unforgiven"],
        ["이게 바로 나야", "Ige baro naya", "This is exactly who I am"],
      ]),
    },
  });

  for (const song of [lsFearless, lsAntifragile, lsEvePsyche, lsUnforgiven]) {
    await prisma.songCredit.upsert({
      where: { id: `credit-${song.slug}-le-sserafim` },
      update: {},
      create: { id: `credit-${song.slug}-le-sserafim`, songId: song.id, artistId: lesserafim.id, role: "performer" },
    });
  }

  console.log("Seeded: IVE, Stray Kids, TXT, ENHYPEN, LE SSERAFIM");
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
